# Generated by Django 2.1.3 on 2018-11-12 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareimages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareiamge',
            name='who_like',
            field=models.ManyToManyField(blank=True, related_name='who_like_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
